import os

from gws_core import (
    BoolParam,
    ConfigParams,
    ConfigSpecs,
    FileHelper,
    InputSpecs,
    OutputSpecs,
    Settings,
    ShellProxy,
    StrParam,
    Task,
    TaskFileDownloader,
    TaskInputs,
    TaskOutputs,
    task_decorator,
)


@task_decorator(
    unique_name="BiotaDbDownloader",
    human_name="Biota DB Downloader",
    short_description="Download and extract the Biota database from a URL",
)
class BiotaDbDownloader(Task):
    """[Generated by Task Expert Agent]

    This task downloads and extracts the Biota MariaDB database from a specified URL.
    It downloads a ZIP file containing the database, extracts it to a designated folder,
    and optionally forces re-download even if the database already exists.

    ## Functionality

    The task performs the following steps:
    1. Downloads the Biota database ZIP file from the provided URL
    2. Extracts the ZIP file to the Biota database folder
    3. Tracks the database version to avoid unnecessary re-downloads
    4. Optionally forces re-download even if the database exists

    ## Parameters

    - **db_url**: The URL to download the Biota database ZIP file from. If not provided, it uses the URL from the brick settings.
    - **force_redownload**: If True, forces re-download even if the database already exists

    ## Output

    Returns information about the download operation including:
    - Download status
    - Database folder path
    - Database URL used

    ## Notes

    - The database version is tracked using a `.version` file in the output folder
    - If the database already exists with the same URL and force_redownload is False, the download is skipped
    - The ZIP file is automatically deleted after extraction
    - Requires the `unzip` command to be available on the system
    """

    input_specs = InputSpecs({})
    output_specs = OutputSpecs({})

    DESTINATION_FOLDER = "db"
    SETTINGS_VARIABLE = "MARIA_DB_URL"

    config_specs = ConfigSpecs(
        {
            "db_url": StrParam(
                human_name="Database URL",
                short_description="URL to download the Biota database ZIP file from. Use url from brick settings if not provided.",
                optional=True,
            ),
            "force_redownload": BoolParam(
                human_name="Force re-download",
                short_description="Force re-download even if the database already exists",
                default_value=False,
            ),
        }
    )

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        db_url: str = params.get_value("db_url")
        force_redownload: bool = params.get_value("force_redownload")

        if not db_url:
            settings_url = Settings.get_instance().get_variable("gws_biota", self.SETTINGS_VARIABLE)
            if not settings_url:
                raise Exception(
                    f"Database URL not provided and not found in settings variable '{self.SETTINGS_VARIABLE}'"
                )
            self.log_info_message(
                f"Using database URL from settings variable '{self.SETTINGS_VARIABLE}': {settings_url}"
            )

            db_url = settings_url

        # Initialize file downloader
        file_downloader = TaskFileDownloader(
            brick_name=self.get_brick_name(),
            message_dispatcher=self.message_dispatcher,
        )

        # Create output folder if it doesn't exist
        destination_folder = os.path.join(
            file_downloader.destination_folder, self.DESTINATION_FOLDER
        )

        mariadb_folder = os.path.join(file_downloader.destination_folder, "mariadb")
        version_file = os.path.join(file_downloader.destination_folder, ".version")

        # Check if re-download is needed
        if not force_redownload and self._db_exists_with_same_version(
            mariadb_folder, version_file, db_url
        ):
            self.log_info_message(
                f"Biota DB already downloaded with the correct version from {db_url}. Skipping download."
            )
            return {}

        # Log start of download
        self.log_info_message(f"Starting Biota DB download from {db_url}")

        # Delete old database folder if it exists
        if FileHelper.exists_on_os(destination_folder):
            self.log_info_message(f"Deleting existing database folder: {destination_folder}")
            FileHelper.delete_dir(destination_folder)
        # if os.path.exists(destination_folder):
        #     self.log_info_message(
        #         f"Deleting existing destination folder: {destination_folder}"
        #     )
        #     FileHelper.delete_dir(destination_folder)

        # if not FileHelper.exists_on_os(destination_folder):

        # Download the ZIP file
        db_folder = file_downloader.download_file_if_missing(
            url=db_url, filename=self.DESTINATION_FOLDER, decompress_file=True
        )

        # Save version information
        self._save_version(version_file, db_url)
        self.log_info_message(f"Saved database version: {db_url}")

        self.log_success_message(
            f"Biota DB successfully downloaded and extracted to {mariadb_folder}"
        )

        return {}

    def _db_exists_with_same_version(
        self, mariadb_folder: str, version_file: str, current_url: str
    ) -> bool:
        """
        Check if the database already exists and has the same version.

        :param mariadb_folder: Path to the MariaDB folder
        :type mariadb_folder: str
        :param version_file: Path to the version file
        :type version_file: str
        :param current_url: Current database URL
        :type current_url: str
        :return: True if database exists with the same version
        :rtype: bool
        """
        if not FileHelper.exists_on_os(mariadb_folder):
            return False

        if not FileHelper.exists_on_os(version_file):
            return False

        try:
            with open(version_file) as f:
                saved_url = f.read().strip()
                return saved_url == current_url
        except Exception:
            return False

    def _save_version(self, version_file: str, db_url: str) -> None:
        """
        Save the database URL to the version file.

        :param version_file: Path to the version file
        :type version_file: str
        :param db_url: Database URL to save
        :type db_url: str
        """
        with open(version_file, "w") as f:
            f.write(db_url)

    def _extract_zip(self, zip_path: str, destination: str) -> None:
        """
        Extract a ZIP file to the destination folder.

        :param zip_path: Path to the ZIP file
        :type zip_path: str
        :param destination: Destination folder for extraction
        :type destination: str
        """
        shell_proxy = ShellProxy(
            working_dir=destination, message_dispatcher=self.message_dispatcher
        )

        # Run unzip command
        result = shell_proxy.run(
            cmd=["unzip", "-q", zip_path, "-d", destination],
            dispatch_stdout=True,
            dispatch_stderr=True,
        )

        if result != 0:
            raise Exception(f"Failed to extract ZIP file. Return code: {result}")
