import os


from gws_biota.db.biota_db_manager import BiotaDbManager
from gws_core import (
    BoolParam,
    ConfigParams,
    ConfigSpecs,
    FileHelper,
    InputSpecs,
    OutputSpecs,
    Settings,
    ShellProxy,
    StrParam,
    Task,
    TaskFileDownloader,
    TaskInputs,
    TaskOutputs,
    task_decorator,
    DockerService,
)
from gws_core import RegisterSQLDBComposeRequestOptionsDTO


@task_decorator(
    unique_name="BiotaDbDownloader",
    human_name="Biota DB Downloader",
    short_description="Download and extract the Biota database from a URL",
)
class BiotaDbDownloader(Task):
    """[Generated by Task Expert Agent]

    This task downloads and extracts the Biota MariaDB database from a specified URL.
    It downloads a ZIP file containing the database, extracts it to a designated folder,
    and optionally forces re-download even if the database already exists.

    ## Functionality

    The task performs the following steps:
    1. Downloads the Biota database ZIP file from the provided URL
    2. Extracts the ZIP file to the Biota database folder
    3. Tracks the database version to avoid unnecessary re-downloads
    4. Optionally forces re-download even if the database exists

    ## Parameters

    - **db_url**: The URL to download the Biota database ZIP file from. If not provided, it uses the URL from the brick settings.
    - **force_redownload**: If True, forces re-download even if the database already exists

    ## Output

    Returns information about the download operation including:
    - Download status
    - Database folder path
    - Database URL used

    ## Notes

    - The database version is tracked using a `.version` file in the output folder
    - If the database already exists with the same URL and force_redownload is False, the download is skipped
    - The ZIP file is automatically deleted after extraction
    - Requires the `unzip` command to be available on the system
    """

    input_specs = InputSpecs({})
    output_specs = OutputSpecs({})

    # Sub folder of brick-data where the DB will be stored and the .version file
    BRICK_DATA_FOLDER = "db"
    # Sub folder inside the DB folder where the mariadb data is stored once unzipped
    MARIA_DB_FOLDER = "mariadb"

    SETTINGS_VARIABLE = "MARIA_DB_URL"

    config_specs = ConfigSpecs(
        {
            "db_url": StrParam(
                human_name="Database URL",
                short_description="URL to download the Biota database ZIP file from. Use url from brick settings if not provided.",
                optional=True,
            ),
            "force_redownload": BoolParam(
                human_name="Force re-download",
                short_description="Force re-download even if the database already exists",
                default_value=False,
            ),
        }
    )

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        db_url: str = params.get_value("db_url")
        force_redownload: bool = params.get_value("force_redownload")

        # Initialize file downloader
        file_downloader = TaskFileDownloader(
            brick_name=self.get_brick_name(),
            message_dispatcher=self.message_dispatcher,
        )

        # Create output folder if it doesn't exist
        brick_data_folder = os.path.join(
            file_downloader.destination_folder, self.BRICK_DATA_FOLDER
        )

        # Clear existing DB if force redownload is requested
        if force_redownload:
            self._clear_db(brick_data_folder)

        # Download and install the database if missing
        self._install_db_if_missing(db_url, file_downloader)

        # Start the Biota DB Docker container
        self._start_db_container()

        # Check Db Manager connection
        self.log_info_message("Verifying Biota database connection...")
        biota_db_manager = BiotaDbManager.get_instance()
        if not biota_db_manager.check_connection():
            raise Exception("Failed to connect to the Biota database after download.")
        self.log_success_message("Successfully connected to the Biota database.")

        return {}

    def _install_db_if_missing(
        self, db_url: str, file_downloader: TaskFileDownloader
    ) -> None:
        if not db_url:
            settings_url = Settings.get_instance().get_variable(
                "gws_biota", self.SETTINGS_VARIABLE
            )
            if not settings_url:
                raise Exception(
                    f"Database URL not provided and not found in settings variable '{self.SETTINGS_VARIABLE}'"
                )
            self.log_info_message(
                f"Using database URL from settings variable '{self.SETTINGS_VARIABLE}': {settings_url}"
            )

            db_url = settings_url

        # Create output folder if it doesn't exist
        brick_data_folder = os.path.join(
            file_downloader.destination_folder, self.BRICK_DATA_FOLDER
        )

        mariadb_folder = os.path.join(brick_data_folder, self.MARIA_DB_FOLDER)
        version_file = os.path.join(brick_data_folder, ".version")

        # Check if re-download is needed
        if self._db_exists_with_same_version(mariadb_folder, version_file, db_url):
            self.log_info_message(
                f"Biota DB already downloaded with the correct version from {db_url}. Skipping download."
            )
            return

        # Log start of download
        self.log_info_message(f"Starting Biota DB download from {db_url}")

        # Download the ZIP file
        db_folder = file_downloader.download_file_if_missing(
            url=db_url, filename=self.BRICK_DATA_FOLDER, decompress_file=True
        )

        mariadb_folder = os.path.join(db_folder, self.MARIA_DB_FOLDER)

        # Check if mariadb folder exists after extraction
        if not FileHelper.exists_on_os(mariadb_folder):
            raise Exception(
                f"Downloaded Biota DB does not contain 'mariadb' folder at expected location: {mariadb_folder}"
            )

        self.log_success_message(
            f"Biota DB successfully downloaded and extracted to {mariadb_folder}"
        )

        # Save the version information
        self._save_version(version_file, db_url)
        self.log_info_message(f"Saved database version: {db_url}")

        return

    def _db_exists_with_same_version(
        self, mariadb_folder: str, version_file: str, current_url: str
    ) -> bool:
        """
        Check if the database already exists and has the same version.

        :param mariadb_folder: Path to the MariaDB folder
        :type mariadb_folder: str
        :param version_file: Path to the version file
        :type version_file: str
        :param current_url: Current database URL
        :type current_url: str
        :return: True if database exists with the same version
        :rtype: bool
        """
        if not FileHelper.exists_on_os(mariadb_folder):
            return False

        if not FileHelper.exists_on_os(version_file):
            return False

        try:
            with open(version_file) as f:
                saved_url = f.read().strip()
                return saved_url == current_url
        except Exception:
            return False

    def _save_version(self, version_file: str, db_url: str) -> None:
        """
        Save the database URL to the version file.

        :param version_file: Path to the version file
        :type version_file: str
        :param db_url: Database URL to save
        :type db_url: str
        """
        with open(version_file, "w") as f:
            f.write(db_url)

    def _extract_zip(self, zip_path: str, destination: str) -> None:
        """
        Extract a ZIP file to the destination folder.

        :param zip_path: Path to the ZIP file
        :type zip_path: str
        :param destination: Destination folder for extraction
        :type destination: str
        """
        shell_proxy = ShellProxy(
            working_dir=destination, message_dispatcher=self.message_dispatcher
        )

        # Run unzip command
        result = shell_proxy.run(
            cmd=["unzip", "-q", zip_path, "-d", destination],
            dispatch_stdout=True,
            dispatch_stderr=True,
        )

        if result != 0:
            raise Exception(f"Failed to extract ZIP file. Return code: {result}")

    def _start_db_container(self) -> None:
        """
        Start the Biota MariaDB Docker container using DockerService.
        """

        docker_service = DockerService()
        docker_service.get_or_create_basic_credentials(
            brick_name=self.get_brick_name(),
            unique_name=BiotaDbManager.get_instance().get_name(),
            url=BiotaDbManager.HOST,
            username=BiotaDbManager.USER,
            password=BiotaDbManager.PASSWORD,
        )

        try:
            docker_service.register_sqldb_compose(
                brick_name=self.get_brick_name(),
                unique_name=BiotaDbManager.get_instance().get_name(),
                database_name=BiotaDbManager.DB_NAME,
                options=RegisterSQLDBComposeRequestOptionsDTO(
                    description="Biota MariaDB database container",
                    auto_start=True,
                    disable_volume_backup=True,
                    all_environments_networks=True,
                    volume_sub_directory=self.MARIA_DB_FOLDER,
                ),
            )

            self.log_info_message("Biota DB container started successfully.")
        except Exception as e:
            self.log_error_message(f"Failed to start Biota DB container: {e}")
            return

    def _clear_db(self, destination_folder: str) -> None:
        """
        Clear the existing database folder.

        :param destination_folder: Path to the database folder
        :type destination_folder: str
        """
        self.log_info_message("Clearing existing database")

        try:
            docker_service = DockerService()
            docker_service.unregister_compose(
                brick_name=self.get_brick_name(),
                unique_name=BiotaDbManager.get_instance().get_name(),
            )
        except Exception as e:
            self.log_info_message(
                f"Failed to unregister Biota DB container before clearing the database: {e}. Continuing with folder deletion."
            )

        if FileHelper.exists_on_os(destination_folder):
            self.log_info_message(
                f"Deleting existing destination folder: {destination_folder}"
            )
            shell_proxy = ShellProxy(
                working_dir="/", message_dispatcher=self.message_dispatcher
            )
            result = shell_proxy.run(
                cmd=["sudo", "rm", "-rf", destination_folder],
                dispatch_stdout=True,
                dispatch_stderr=True,
            )
            if result != 0:
                raise Exception(
                    f"Failed to delete directory {destination_folder}. Return code: {result}"
                )
